dist: xenial
language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"    
install:
    - pip install --upgrade -r requirements.txt
    - pip install -e .
script:
    coverage run -m unittest discover -v
after_success:
    coveralls

